apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: slingshot-scheduler 
 
resources:
 - ./samplecronjob-deployment.yml
 - ./scheduleconsumer-deployment.yml
 - ./schedulequeue-deployment.yml

#patchesStrategicMerge:
#no patches - just local sample deployment