apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: slingshot-scheduler 
 
resources:
 - ./samplecronjob-deployment.yml
 - ./scheduleconsumer-deployment.yml
 - ./schedulequeue-deployment.yml
 - ./schedulequeue-service.yml

#patchesStrategicMerge:
#no patches - just local sample deployment


configMapGenerator:

  - behavior: create
    name: scheduler-config
    literals:
      - QUEUE_PORT="9324" 
      - QUEUE_HOST="alpine-sqs"